version: '3.9'
services:
  nginx:
    build: /data/web/sites/nullWebsite/nginx/ 
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/web/sites/nullWebsite/cert:/data/cert:ro
      - /data/web/sites/nullWebsite/html:/data/html:ro
    restart: unless-stopped
